DacodesApi/urls.py
#Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
#Djangorestframework
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework.documentation import include_docs_urls
urlpatterns = [
    # JWT urls
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # Include Frontend urls
    path('', include(('courses.urls', 'courses'), namespace='courses')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    # API v1 url
    path('api/v1/', include('core.urls.v1')),
    # Admin module url
    path('admin/', admin.site.urls),
    # API documentation for Frontend team
    path('documentation/', include_docs_urls(title='Dacodes API', public=True))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
# Django
from django.urls import path

# Views
from .views import CourseListView, CourseDetailView, LessonDetailView

# Frontend urls
urlpatterns = [
    path('', CourseListView.as_view(), name='courses'),
    path('course/<int:pk>/', CourseDetailView.as_view(), name='courses-detail'),
    path('course/<int:pk>/questions', LessonDetailView.as_view(), name='lessons-detail')
]

users/urls.py
# Django
from django.urls import path

# View
from users import views


urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
]

templates/base.html
<!Doctype html>
<html lang="en">
<head>

     <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    {% if title %}
        <title>Dacodes.com - {{ title }}</title>
    {% else %}
        <title>Dacodes.com</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        {% include "nav.html" %}
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages%}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
         <div class="col-md-4">
            <img src="https://dacodes.com/wp-content/uploads/2020/02/Captura-de-Pantalla-2019-11-27-a-las-3.39.41-p.-m..png" alt="Dacodes Logo" class="img-thumbnail">
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/nav.html
 <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'courses:courses' %}">Dacodes.com</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{% url 'users:logout' %}">Log out</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
            </div>
          </div>
        </div>
 </nav>